#!/bin/sh

set -e

## Alpine deps
apk add --update -t build-deps git mercurial bzr make vim
apk add -u musl tar

## apk GO version check
#if [ -s Makefile ]; then
#    goVersion="$(make -f Makefile -f /bin/helper.mak print-GO_VERSION)"
#    if [ "$goVersion" = "$(apk info go -s | sed -e 's/^[^0-9.]*\([0-9.]*\).*/\1/' | head -1)" ]; then
#        apk add -t build-deps go
#    else
#        # Get deps for go src build
#        apk add -t build-deps gcc libgcc musl-dev curl patch perl bash
#    fi
#fi

## GO Magic
goBin="/bin/app"
if [ -s Makefile ]; then
    binary="$(make -f Makefile -f /bin/helper.mak print-BINARY)"
    target="$(make -f Makefile -f /bin/helper.mak print-TARGET)"

    if [ "$target" ]; then
	goBin="/bin/$target"
    fi
fi

#make -f Makefile -f /bin/build_go_src.mak
make -f Makefile
cp "$binary" "$goBin"

# Store the binary name in a temp file for the go-run script
echo "$goBin" > /tmp/go-bin-name

## Cleanup Alpine deps
apk del --purge build-deps
rm -rf /app /var/cache/apk/*
